name: OneSTools.EventLog.Exporter.Core (.NET 5)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      working-directory: ./OneSTools.EventLog.Exporter.Core
      run: dotnet restore
    - name: Build
      working-directory: ./OneSTools.EventLog.Exporter.Core
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./OneSTools.EventLog.Exporter.Core
      run: dotnet test --no-restore --verbosity normal
